import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/react"; // Example import, adjust as needed
import Link from "next/link"; // Import Link from next/link

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ivene 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} min-h-screen flex flex-col`}>
          <Toaster />
          <div className="flex-grow">
            {children}
          </div>
          <footer className="text-center py-4">
            &copy; {new Date().getFullYear()} Copyright by <Link href="mailto:sohamchavan0629@gmail.com">Soham Chavan</Link>
          </footer>
          <Analytics debug={false}/> {/* Add Analytics here */}
        </body>
      </html>
    </ClerkProvider>
  );
}
